import type {
  FormElementOrList,
  FormObject,
  FormStep,
} from "@/form-builder/form-types";

export const templates: FormObject[] = [
  {
    id: "template-signup",
    title: "Signup Form",
    isMS: false,
    formElements: [
      {
        id: "signup-heading",
        name: "Heading",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Sign Up",
      },
      {
        id: "signup-paragraph",
        name: "Paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "You need an account to get started",
      },
      {
        id: "signup-firstname",
        name: "firstname",
        fieldType: "Input",
        type: "text",
        label: "First Name",
        placeholder: "Enter your First Name",
        required: true,
      },
      {
        id: "signup-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email",
        placeholder: "Enter your Email",
        required: true,
      },
      [
        {
          id: "signup-password",
          name: "password",
          fieldType: "Password",
          type: "password",
          label: "Password",
          placeholder: "Password",
          required: true,
        },
        {
          id: "signup-password-confirm",
          name: "confirm-password",
          fieldType: "Password",
          type: "password",
          label: "Confirm Password",
          placeholder: "Confirm Password",
          required: true,
        },
      ],
      {
        id: "signup-agree",
        name: "agree",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-login",
    title: "Login Form",
    isMS: false,
    formElements: [
      {
        id: "login-heading",
        name: "login",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Login",
      },
      {
        id: "sign-up-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Login to create an account",
      },
      {
        id: "login-email",
        name: "email",
        label: "Email",
        fieldType: "Input",
        type: "email",
        placeholder: "Enter your Email",
      },
      {
        id: "login-password",
        name: "password",
        fieldType: "Password",
        placeholder: "Password",
        label: "Password",
        type: "password",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-feedback-form",
    title: "Feedback Form",
    isMS: false,
    formElements: [
      {
        id: "feedback-heading",
        name: "feedback",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Feedback Form",
      },
      {
        id: "feedback-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please provide your feedback",
      },
      {
        id: "feedback-comment",
        name: "comment",
        fieldType: "Textarea",
        placeholder: "Share your feedback",
        label: "Feedback Comment",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-waitlist",
    title: "Waitlist",
    isMS: false,
    formElements: [
      {
        id: "waitlist-heading",
        name: "heading",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Waitlist",
      },
      {
        id: "waitlist-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Join our waitlist to get early access",
      },
      {
        id: "waitlist-email",
        name: "email",
        label: "Your Email",
        fieldType: "Input",
        type: "email",
        placeholder: "Enter your Email",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-contact-us",
    title: "Contact Us",
    isMS: false,
    formElements: [
      {
        id: "contact-heading",
        name: "heading",
        fieldType: "Text",
        variant: "H2",
        static: true,
        content: "Contact us",
      },
      {
        id: "contact-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please fill the form below to contact us",
      },
      [
        {
          id: "contact-name",
          name: "name",
          fieldType: "Input",
          type: "text",
          label: "Name",
          required: true,
          placeholder: "Enter your name",
        },
        {
          id: "contact-email",
          name: "email",
          fieldType: "Input",
          type: "email",
          label: "Email",
          required: true,
          placeholder: "Enter your email",
        },
      ],
      {
        id: "contact-message",
        name: "message",
        fieldType: "Textarea",
        label: "Message",
        placeholder: "Enter your message",
        required: true,
      },
      {
        id: "contact-agree",
        name: "agree",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-multi-step-form",
    title: "Survey Form",
    isMS: true,
    formElements: [
      {
        id: "survey-step-1",
        stepFields: [
          {
            id: "survey-personal-heading",
            name: "heading-2",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Personal Details",
          },
          {
            id: "survey-personal-paragraph",
            name: "paragraph",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your personal details",
          },
          {
            id: "survey-first-name",
            name: "first-name",
            fieldType: "Input",
            placeholder: "First name",
            label: "First name",
            required: true,
          },
          {
            id: "survey-last-name",
            name: "last-name",
            fieldType: "Input",
            placeholder: "Last name",
            label: "Last name",
          },
        ],
      },
      {
        id: "survey-step-2",
        stepFields: [
          {
            id: "survey-contact-heading",
            name: "heading-2",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Contact Information",
          },
          {
            id: "survey-contact-paragraph",
            name: "paragraph",
            fieldType: "Text",
            variant: "P",
            static: true,
            content: "Please provide your contact information",
          },
          {
            id: "survey-contact-email",
            name: "your-email",
            fieldType: "Input",
            label: "Your Email",
            type: "email",
            required: true,
            placeholder: "Enter your email",
          },
          {
            id: "survey-contact-phone",
            name: "phone-number",
            fieldType: "Input",
            label: "Phone Number",
            type: "number",
            placeholder: "Enter your phone number",
          },
        ],
      },
      {
        id: "survey-step-3",
        stepFields: [
          {
            name: "step-2",
            id: "survey-preferences-heading",
            fieldType: "Text",
            variant: "H2",
            static: true,
            content: "Your Preferences",
          },
          {
            id: "survey-preferences-toggle",
            name: "preferences",
            fieldType: "ToggleGroup",
            type: "multiple",
            label: "Tell us about your interests and preferences.",
            options: [
              { label: "Technology", value: "technology" },
              { label: "Business", value: "Business" },
              { label: "Health", value: "Health" },
              { label: "Science", value: "Science" },
            ],
          },
          {
            id: "survey-preferences-comment",
            name: "Comment",
            fieldType: "Textarea",
            placeholder: "Share your feedback",
            label: "Feedback Comment",
          },
        ],
      },
    ] as FormStep[],
  } as FormObject,
  {
    id: "template-job-application",
    title: "Job Application",
    isMS: false,
    formElements: [
      {
        id: "job-heading",
        name: "job-application",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Job Application",
      },
      {
        id: "job-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Please fill out the form below to apply for this position",
      },
      [
        {
          id: "job-first-name",
          name: "firstName",
          fieldType: "Input",
          type: "text",
          label: "First Name",
          required: true,
          placeholder: "Enter your first name",
        },
        {
          id: "job-last-name",
          name: "lastName",
          fieldType: "Input",
          type: "text",
          label: "Last Name",
          required: true,
          placeholder: "Enter your last name",
        },
      ],
      {
        id: "job-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "github-url",
        name: "github-url",
        fieldType: "Input",
        type: "url",
        label: "GitHub URL",
        required: false,
        placeholder: "Enter your GitHub URL",
      },
      {
        id: "linkedin-url",
        name: "linkedin-url",
        fieldType: "Input",
        type: "url",
        label: "LinkedIn URL",
        required: false,
        placeholder: "Enter your LinkedIn URL",
      },
      {
        id: "job-position",
        name: "position",
        fieldType: "RadioGroup",
        // placeholder: "Select Position",
        label: "Which position are you applying for?",
        required: true,
        options: [
          { label: "Frontend Developer", value: "frontend" },
          { label: "Backend Developer", value: "backend" },
          { label: "Full Stack Developer", value: "fullstack" },
          { label: "UI/UX Designer", value: "designer" },
          { label: "Product Manager", value: "pm" },
        ],
      },
      {
        id: "job-experience",
        name: "experience",
        fieldType: "Select",
        placeholder: "Select Experience",
        label: "Years of Experience",
        required: true,
        options: [
          { label: "0-1 years", value: "0-1" },
          { label: "2-3 years", value: "2-3" },
          { label: "4-5 years", value: "4-5" },
          { label: "6-10 years", value: "6-10" },
          { label: "10+ years", value: "10+" },
        ],
      },
      {
        id: "file-upload",
        name: "file-upload",
        fieldType: "FileUpload",
        label: "Attach Resume",
        placeholder: "PDF, DOC or DOCX (max. 5MB)",
        accept: "application/pdf, application/doc, application/docx",
      },
      {
        id: "job-cover-letter",
        name: "cover-letter",
        fieldType: "Textarea",
        label: "Cover Letter",
        placeholder: "Tell us why you're interested in this position...",
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-event-registration",
    title: "Event Registration",
    isMS: false,
    formElements: [
      {
        id: "event-heading",
        name: "event-registration",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Event Registration",
      },
      {
        id: "event-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Register for our upcoming event",
      },
      [
        {
          id: "event-first-name",
          name: "firstName",
          fieldType: "Input",
          type: "text",
          label: "First Name",
          required: true,
          placeholder: "Enter your first name",
        },
        {
          id: "event-last-name",
          name: "lastName",
          fieldType: "Input",
          type: "text",
          label: "Last Name",
          required: true,
          placeholder: "Enter your last name",
        },
      ],
      {
        id: "event-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "event-company",
        name: "company",
        fieldType: "Input",
        type: "text",
        label: "Company/Organization",
        placeholder: "Enter your company name",
      },
      {
        id: "event-ticket-type",
        name: "ticket-type",
        fieldType: "RadioGroup",
        label: "Ticket Type",
        required: true,
        options: [
          { label: "General Admission - Free", value: "general" },
          { label: "VIP Access - $99", value: "vip" },
          { label: "Premium Package - $199", value: "premium" },
        ],
      },
      {
        id: "event-comments",
        name: "comments",
        fieldType: "Textarea",
        label: "Additional Comments",
        placeholder: "Any special requirements or questions?",
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-product-order",
    title: "Product Order",
    isMS: false,
    formElements: [
      {
        id: "order-heading",
        name: "product-order",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Place Your Order",
      },
      {
        id: "order-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "Fill out the details below to complete your order",
      },
      {
        id: "order-product",
        name: "product",
        fieldType: "Select",
        label: "Select Product",
        placeholder: "Select Product",
        required: true,
        options: [
          { label: "Basic Plan - $29/month", value: "basic" },
          { label: "Pro Plan - $59/month", value: "pro" },
          { label: "Enterprise Plan - $99/month", value: "enterprise" },
        ],
      },
      [
        {
          id: "order-first-name",
          name: "firstName",
          fieldType: "Input",
          type: "text",
          label: "First Name",
          required: true,
          placeholder: "Enter your first name",
        },
        {
          id: "order-last-name",
          name: "lastName",
          fieldType: "Input",
          type: "text",
          label: "Last Name",
          required: true,
          placeholder: "Enter your last name",
        },
      ],
      {
        id: "order-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "order-billing-address",
        name: "billing-address",
        fieldType: "Textarea",
        label: "Billing Address",
        required: true,
        placeholder: "Enter your complete billing address",
      },
      {
        id: "order-payment-method",
        name: "payment-method",
        fieldType: "RadioGroup",
        label: "Payment Method",
        required: true,
        options: [
          { label: "Credit Card", value: "credit" },
          { label: "PayPal", value: "paypal" },
          { label: "Bank Transfer", value: "bank" },
        ],
      },
      {
        id: "order-terms",
        name: "terms",
        fieldType: "Checkbox",
        label: "I agree to the terms and conditions",
        required: true,
      },
    ] as FormElementOrList[],
  } as FormObject,
  {
    id: "template-customer-support",
    title: "Customer Support",
    isMS: false,
    formElements: [
      {
        id: "support-heading",
        name: "customer-support",
        fieldType: "Text",
        variant: "H1",
        static: true,
        content: "Customer Support Request",
      },
      {
        id: "support-paragraph",
        name: "paragraph",
        fieldType: "Text",
        variant: "P",
        static: true,
        content: "We're here to help! Please describe your issue below.",
      },
      [
        {
          id: "support-first-name",
          name: "firstName",
          fieldType: "Input",
          type: "text",
          label: "First Name",
          required: true,
          placeholder: "Enter your first name",
        },
        {
          id: "support-last-name",
          name: "lastName",
          fieldType: "Input",
          type: "text",
          label: "Last Name",
          required: true,
          placeholder: "Enter your last name",
        },
      ],
      {
        id: "support-email",
        name: "email",
        fieldType: "Input",
        type: "email",
        label: "Email Address",
        required: true,
        placeholder: "Enter your email address",
      },
      {
        id: "support-order-number",
        name: "order-number",
        fieldType: "Input",
        type: "text",
        label: "Order Number (if applicable)",
        placeholder: "Enter your order number",
      },
      {
        id: "support-category",
        name: "category",
        fieldType: "Select",
        placeholder: "Select Category",
        label: "Issue Category",
        required: true,
        options: [
          { label: "Technical Issue", value: "technical" },
          { label: "Billing Question", value: "billing" },
          { label: "Product Inquiry", value: "product" },
          { label: "Account Access", value: "account" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "support-priority",
        name: "priority",
        fieldType: "RadioGroup",
        label: "Priority Level",
        required: true,
        options: [
          { label: "Low - General inquiry", value: "low" },
          { label: "Medium - Issue affecting usage", value: "medium" },
          { label: "High - Urgent issue", value: "high" },
        ],
      },
      {
        id: "support-description",
        name: "description",
        fieldType: "Textarea",
        label: "Issue Description",
        required: true,
        placeholder: "Please describe your issue in detail...",
      },
    ] as FormElementOrList[],
  } as FormObject,
];
